force-app/main/default/objects/Timecard__c/Timecard__c.object-meta.xml
<CustomObject>
    <label>Timecard</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>Timecard Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timecards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Timecard__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sickleave</fullName>
            </value>
            <value>
                <fullName>Sickleave without Document</fullName>
            </value>
            <value>
                <fullName>Vacation</fullName>
            </value>
            <value>
                <fullName>Unpaid Leave</fullName>
            </value>
            <value>
                <fullName>Client Project</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Maternity Leave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InternalTimecardController.cls
public with sharing class InternalTimecardController {
    @AuraEnabled(cacheable=true)
    public static List<String> getTimecardTypes() {
        List<String> timecardTypes = new List<String>();
        Schema.DescribeFieldResult fieldResult = Timecard__c.Type__c.getDescribe();

        // Retrieve picklist values and filter out "Client Project"
        for (Schema.PicklistEntry entry : fieldResult.getPicklistValues()) {
            if (entry.getValue() != 'Client Project') {
                timecardTypes.add(entry.getValue());
            }
        }
        return timecardTypes;
    }

    @AuraEnabled
    public static Id createTimecard(String type, Date startDate, Date endDate, Id userId) {
        return Utilities.createAbsence(type, startDate, endDate, userId);
    }

}