force-app/main/default/objects/Holidays__c/Holidays__c.object-meta.xml
<CustomObject>
    <label>Holidays</label>
    <nameField>
        <label>Holidays Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Holidays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Holidays__c/fields/Work_Calendar__c.field-meta.xml
<CustomField>
    <fullName>Work_Calendar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Calendar</label>
    <referenceTo>Work_Calendar__c</referenceTo>
    <relationshipLabel>Holidays</relationshipLabel>
    <relationshipName>Holidays</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Internal_Activities__c/Internal_Activities__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Internal Activities</label>
</CustomObject>

force-app/main/default/objects/Internal_Activities__c/fields/Availability_Field__c.field-meta.xml
<CustomField>
    <fullName>Availability_Field__c</fullName>
    <label>Availability Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Internal_Activities__c/fields/Project_Id__c.field-meta.xml
<CustomField>
    <fullName>Project_Id__c</fullName>
    <label>Project Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/Work_Calendar__c.field-meta.xml
<CustomField>
    <fullName>Work_Calendar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Calendar</label>
    <referenceTo>Work_Calendar__c</referenceTo>
    <relationshipLabel>Regions</relationshipLabel>
    <relationshipName>Regions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timecard__c/Timecard__c.object-meta.xml
<CustomObject>
    <label>Timecard</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>Timecard Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timecards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Timecard__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Timecards</relationshipLabel>
    <relationshipName>Timecards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Timecard__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Timecards</relationshipLabel>
    <relationshipName>Timecards</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timecard__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sickleave</fullName>
            </value>
            <value>
                <fullName>Sickleave without Document</fullName>
            </value>
            <value>
                <fullName>Vacation</fullName>
            </value>
            <value>
                <fullName>Unpaid Leave</fullName>
            </value>
            <value>
                <fullName>Client Project</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Maternity Leave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Calendar__c/Work_Calendar__c.object-meta.xml
<CustomObject>
    <label>Work Calendar</label>
    <nameField>
        <label>Work Calendar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Calendar__c/fields/Monday_Hours__c.field-meta.xml
<CustomField>
    <fullName>Monday_Hours__c</fullName>
    <label>Monday Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Work_Calendar__c/fields/Saturday_Hours__c.field-meta.xml
<CustomField>
    <fullName>Saturday_Hours__c</fullName>
    <label>Saturday Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Work_Calendar__c/fields/Thursday_Hours__c.field-meta.xml
<CustomField>
    <fullName>Thursday_Hours__c</fullName>
    <label>Thursday Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Work_Calendar__c/fields/Tuesday_Hours__c.field-meta.xml
<CustomField>
    <fullName>Tuesday_Hours__c</fullName>
    <label>Tuesday Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Work_Calendar__c/fields/Wednesday_Hours__c.field-meta.xml
<CustomField>
    <fullName>Wednesday_Hours__c</fullName>
    <label>Wednesday Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Utilities.cls
public with sharing class Utilities {

    public static Set<Date> getHolidays( Id workCalendarId ) {
        Set<Date> holidays = new Set<Date>();
        List<Holidays__c> holidaysList = [SELECT Date__c FROM Holidays__c WHERE Work_Calendar__c = :workCalendarId];
        for (Holidays__c holiday : holidaysList) {
            holidays.add(holiday.Date__c);
        }
        return holidays;
    }

    public static Work_Calendar__c getWorkCalendarForRegion( Id regionId ) {
        return [
                SELECT Id, Monday_Hours__c, Tuesday_Hours__c, Wednesday_Hours__c,
                        Thursday_Hours__c, Friday_Hours__c, Saturday_Hours__c, Sunday_Hours__c
                FROM Work_Calendar__c
                WHERE Id IN (SELECT Work_Calendar__c FROM Region__c WHERE Id = :regionId)
                LIMIT 1
        ];
    }

    public static Work_Calendar__c getWorkCalendar( Id calendarId ) {
        return [
                SELECT Id, Monday_Hours__c, Tuesday_Hours__c, Wednesday_Hours__c,
                        Thursday_Hours__c, Friday_Hours__c, Saturday_Hours__c, Sunday_Hours__c
                FROM Work_Calendar__c
                WHERE Id = :calendarId
                LIMIT 1
        ];
    }

    public static Map<String, Decimal> getRequiredHours( Work_Calendar__c workCalendar ) {
        Map<String, Decimal> dailyHours = new Map<String, Decimal>{
                'Monday'    => workCalendar.Monday_Hours__c,
                'Tuesday'   => workCalendar.Tuesday_Hours__c,
                'Wednesday' => workCalendar.Wednesday_Hours__c,
                'Thursday'  => workCalendar.Thursday_Hours__c,
                'Friday'    => workCalendar.Friday_Hours__c,
                'Saturday'  => workCalendar.Saturday_Hours__c,
                'Sunday'    => workCalendar.Sunday_Hours__c
        };

        return dailyHours;
    }

    public static Map<String, Internal_Activities__c> getInternalActivitiesProjectMap() {
        Map<String, Internal_Activities__c> internalActivitiesProjectMap = new Map<String, Internal_Activities__c>();
        for( Internal_Activities__c internalActivity : Internal_Activities__c.getAll().values() ) {
            internalActivitiesProjectMap.put( internalActivity.Name, internalActivity );
        }
        return internalActivitiesProjectMap;
    }

    public static Id createAbsence( String type, Date startDate, Date endDate, Id userId ) {
        Internal_Activities__c targetActivity = getInternalActivitiesProjectMap().get( type );
        String resourceQuery = 'SELECT Id, Region__c, Region__r.Work_Calendar__c' + ( String.isNotBlank( targetActivity.Availability_Field__c ) ? ( ', ' + targetActivity.Availability_Field__c ) : '' ) + ' FROM Resource__c WHERE User__c = :userId LIMIT 1';
        Resource__c currentResource = Database.query( resourceQuery );
        Integer availableAbsences = null;
        if( String.isNotBlank( targetActivity.Availability_Field__c ) ) {
            availableAbsences = Integer.valueOf( currentResource.get( targetActivity.Availability_Field__c ) );
        }
        if (currentResource == null) {
            throw new IllegalArgumentException('Resource not found for the current user');
        }
        List<Timecard__c> timecardsToInsert = new List<Timecard__c>();
        Set<Date> holidays = Utilities.getHolidays( currentResource.Region__r.Work_Calendar__c );
        Map<String, Decimal> requiredHours = getRequiredHours( getWorkCalendarForRegion( currentResource.Region__c ) );

        Project__c curProject = [SELECT Id, OwnerId FROM Project__c WHERE Id = :targetActivity.Project_Id__c LIMIT 1];

        Integer daysCounter = 0;
        Date currentStartDate = startDate;
        while( currentStartDate <= endDate ) {
            Date startOfWeek = currentStartDate.toStartOfWeek();
            Integer currentDayOfWeek = startOfWeek.daysBetween( currentStartDate );
            Date endOfWeek = startOfWeek.addDays( 6 );
            Timecard__c curCart = new Timecard__c(
                    Resource__c = currentResource.Id,
                    Type__c = type,
                    Start_Date__c = startOfWeek,
                    End_Date__c = endOfWeek,
                    Status__c = 'New',
                    Project__c = targetActivity.Project_Id__c,
                    Monday_Hours__c = 0,
                    Tuesday_Hours__c = 0,
                    Wednesday_Hours__c = 0,
                    Thursday_Hours__c = 0,
                    Friday_Hours__c = 0,
                    Saturday_Hours__c = 0,
                    Sunday_Hours__c = 0
            );

            for( Integer i = currentDayOfWeek; i < 7; i++ ) {
                Date currentDate = startOfWeek.addDays( i );
                if( holidays.contains( currentDate ) ) {
                    continue;
                }

                if( currentDate > endDate ) {
                    break;
                }
                // Populate hours based on the day of the week
                switch on i {
                    when 0  { curCart.Monday_Hours__c    = requiredHours.get('Monday'); if( requiredHours.get('Monday') != 0 ) { daysCounter++; } }
                    when 1  { curCart.Tuesday_Hours__c   = requiredHours.get('Tuesday'); if( requiredHours.get('Tuesday') != 0 ) { daysCounter++; } }
                    when 2  { curCart.Wednesday_Hours__c = requiredHours.get('Wednesday'); if( requiredHours.get('Wednesday') != 0 ) { daysCounter++; } }
                    when 3  { curCart.Thursday_Hours__c  = requiredHours.get('Thursday'); if( requiredHours.get('Thursday') != 0 ) { daysCounter++; } }
                    when 4  { curCart.Friday_Hours__c    = requiredHours.get('Friday'); if( requiredHours.get('Friday') != 0 ) { daysCounter++; } }
                    when 5  { curCart.Saturday_Hours__c  = requiredHours.get('Saturday'); if( requiredHours.get('Saturday') != 0 ) { daysCounter++; } }
                    when 6  { curCart.Sunday_Hours__c    = requiredHours.get('Sunday'); if( requiredHours.get('Sunday') != 0 ) { daysCounter++; } }
                }

                if( availableAbsences != null && availableAbsences < daysCounter ) {
                    throw new IllegalArgumentException('Unable to book Absence. Not enough available days.');
                }
            }

            timecardsToInsert.add(curCart);

            currentStartDate = currentDayOfWeek == 0 ? currentStartDate.addDays( 7 ) : currentStartDate.addDays( 7 - currentDayOfWeek );
        }

        insert timecardsToInsert;

        if( String.isNotBlank( targetActivity.Availability_Field__c ) && availableAbsences != null ) {
            Integer remainingAbs =  availableAbsences - daysCounter;
            currentResource.put( targetActivity.Availability_Field__c, Decimal.valueOf( remainingAbs.toString() ) );
            update  currentResource;
        }

        // Submit for approval and assign a specific user or queue as the approver
        List<Approval.ProcessRequest> recordsForApproval = new List<Approval.ProcessRequest>();
        for( Timecard__c curCart : timecardsToInsert ) {
            Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
            req.setObjectId( curCart.Id );
            List<Id> approverIds = new List<Id>{ curProject.OwnerId };
            req.setNextApproverIds(approverIds);

            recordsForApproval.add( req );
        }

        List<Approval.ProcessResult> result = Approval.process( recordsForApproval );
        for( Approval.ProcessResult res : result ) {
            if( !res.isSuccess() ) {
                System.debug( 'Error: ' + res.getErrors()[0].getMessage() );
            }
        }

        return timecardsToInsert[0]?.Id;
    }
}