force-app/main/default/objects/Region__c/fields/Work_Calendar__c.field-meta.xml
<CustomField>
    <fullName>Work_Calendar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Calendar</label>
    <referenceTo>Work_Calendar__c</referenceTo>
    <relationshipLabel>Regions</relationshipLabel>
    <relationshipName>Regions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource__c/fields/Is_Resource__c.field-meta.xml
<CustomField>
    <fullName>Is_Resource__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Resource</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Resource__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timecard__c/Timecard__c.object-meta.xml
<CustomObject>
    <label>Timecard</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>Timecard Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timecards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Timecard__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Timecards</relationshipLabel>
    <relationshipName>Timecards</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timecard__c/fields/Total_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Hours__c</fullName>
    <formula>Monday_Hours__c + Tuesday_Hours__c + Wednesday_Hours__c + Thursday_Hours__c + Friday_Hours__c + Saturday_Hours__c + Sunday_Hours__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Violation__c/Violation__c.object-meta.xml
<CustomObject>
    <label>Violation</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Violation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Violations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Violation__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Violations</relationshipLabel>
    <relationshipName>Violations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Violation__c/fields/Week_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Week_End_Date__c</fullName>
    <label>Week End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Violation__c/fields/Week_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Week_Start_Date__c</fullName>
    <label>Week Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Calendar__c/Work_Calendar__c.object-meta.xml
<CustomObject>
    <label>Work Calendar</label>
    <nameField>
        <label>Work Calendar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ViolationJob.cls
public with sharing class ViolationJob implements Database.Batchable<SObject>, Schedulable  {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        // Get Timecards from last week
        Date lastSunday = Date.today().toStartOfWeek().addDays(-1);
        Date lastMonday = lastSunday.addDays(-6);

        return Database.getQueryLocator([
                SELECT Id, Region__r.Work_Calendar__r.Total_Hours__c, Email__c, User__r.Email, (SELECT Id, Total_Hours__c FROM Timecards__r WHERE Start_Date__c =: lastMonday AND End_Date__c =: lastSunday) FROM Resource__c WHERE Is_Resource_Active__c = TRUE AND  Is_Resource__c = TRUE
        ]);
    }

    public void execute(Database.BatchableContext bc, List<Resource__c> scope) {
        List<Violation__c> violationsToInsert = new List<Violation__c>();
        List<Messaging.SingleEmailMessage> violationMessages = new List<Messaging.SingleEmailMessage>();
        for (Resource__c curRes : scope) {
            List<Timecard__c> relatedTimecards = curRes.Timecards__r;
            if( relatedTimecards == null || relatedTimecards.isEmpty() ) {
                violationsToInsert.add( new Violation__c(
                        Resource__c = curRes.Id,
                        Week_Start_Date__c = Date.today().toStartOfWeek().addDays(-7),
                        Week_End_Date__c = Date.today().toStartOfWeek().addDays(-1),
                        Total_Hours__c =  curRes.Region__r.Work_Calendar__r.Total_Hours__c
                ));
            }

            Decimal totalHours = 0;
            for( Timecard__c curCart : relatedTimecards ) {
                totalHours += curCart.Total_Hours__c;
            }

            if ( totalHours < curRes.Region__r.Work_Calendar__r.Total_Hours__c ) {
                violationsToInsert.add( new Violation__c(
                        Resource__c = curRes.Id,
                        Week_Start_Date__c = Date.today().toStartOfWeek().addDays(-7),
                        Week_End_Date__c = Date.today().toStartOfWeek().addDays(-1),
                        Total_Hours__c = ( curRes.Region__r.Work_Calendar__r.Total_Hours__c - totalHours )
                ));

                if( String.isNotBlank( curRes.Email__c ) ||  String.isNotBlank( curRes.User__r.Email ) ) {
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

                    mail.setToAddresses(new String[] { String.isNotBlank( curRes.Email__c ) ? curRes.Email__c : curRes.User__r.Email });
                    mail.setSubject('Timelog Violation Notification');
                    mail.setPlainTextBody('You timelog not completed for previous week. Please fix it. Remaining hours to log: ' + ( curRes.Region__r.Work_Calendar__r.Total_Hours__c - totalHours ) );
                    violationMessages.add(mail);
                }
            }
        }
        System.debug( violationMessages );
        System.debug( violationsToInsert );
        insert violationsToInsert;
        Messaging.sendEmail( violationMessages );
    }

    public void finish(Database.BatchableContext bc) {

    }

    public void execute(SchedulableContext context) {
        ViolationJob batch = new ViolationJob();
        Database.executeBatch(batch, 200);
    }
}