force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assignment__c/fields/Overtime__c.field-meta.xml
<CustomField>
    <fullName>Overtime__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Overtime</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/Percent_Allocated__c.field-meta.xml
<CustomField>
    <fullName>Percent_Allocated__c</fullName>
    <label>Percent Allocated</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>On Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/Total_Billiable_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Billiable_Amount__c</fullName>
    <formula>Billiable_Hours_Submitted__c * Resource_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Billiable Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/Work_Calendar__c.field-meta.xml
<CustomField>
    <fullName>Work_Calendar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Calendar</label>
    <referenceTo>Work_Calendar__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Holidays__c/Holidays__c.object-meta.xml
<CustomObject>
    <label>Holidays</label>
    <nameField>
        <label>Holidays Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Holidays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Holidays__c/fields/Work_Calendar__c.field-meta.xml
<CustomField>
    <fullName>Work_Calendar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Calendar</label>
    <referenceTo>Work_Calendar__c</referenceTo>
    <relationshipLabel>Holidays</relationshipLabel>
    <relationshipName>Holidays</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Internal_Activities__c/Internal_Activities__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Internal Activities</label>
</CustomObject>

force-app/main/default/objects/Internal_Activities__c/fields/Allowed_Absence_Field__c.field-meta.xml
<CustomField>
    <fullName>Allowed_Absence_Field__c</fullName>
    <label>Allowed Absence Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Internal_Activities__c/fields/Availability_Field__c.field-meta.xml
<CustomField>
    <fullName>Availability_Field__c</fullName>
    <label>Availability Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <label>Milestone</label>
    <nameField>
        <label>Milestore Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Milestones</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Daily_Timecart_Notes_Required__c.field-meta.xml
<CustomField>
    <fullName>Daily_Timecart_Notes_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Daily Timecart Notes Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/Work_Calendar__c.field-meta.xml
<CustomField>
    <fullName>Work_Calendar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Calendar</label>
    <referenceTo>Work_Calendar__c</referenceTo>
    <relationshipLabel>Regions</relationshipLabel>
    <relationshipName>Regions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timecard__c/Timecard__c.object-meta.xml
<CustomObject>
    <label>Timecard</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>Timecard Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timecards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Timecard__c/fields/Assignment__c.field-meta.xml
<CustomField>
    <fullName>Assignment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Assignment</label>
    <referenceTo>Assignment__c</referenceTo>
    <relationshipLabel>Timecards</relationshipLabel>
    <relationshipName>Timecards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timecard__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Milestone</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>Timecards</relationshipLabel>
    <relationshipName>Timecards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timecard__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Timecards</relationshipLabel>
    <relationshipName>Timecards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Timecard__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Timecards</relationshipLabel>
    <relationshipName>Timecards</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timecard__c/fields/Total_Billiable_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Billiable_Amount__c</fullName>
    <formula>( Monday_Hours__c + Tuesday_Hours__c + Wednesday_Hours__c +  Thursday_Hours__c + Friday_Hours__c +  Saturday_Hours__c + Sunday_Hours__c ) *  Assignment__r.Resource_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Billiable Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Timecard__c/fields/Total_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Hours__c</fullName>
    <formula>Monday_Hours__c + Tuesday_Hours__c + Wednesday_Hours__c + Thursday_Hours__c + Friday_Hours__c + Saturday_Hours__c + Sunday_Hours__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Timecard__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sickleave</fullName>
            </value>
            <value>
                <fullName>Sickleave without Document</fullName>
            </value>
            <value>
                <fullName>Vacation</fullName>
            </value>
            <value>
                <fullName>Unpaid Leave</fullName>
            </value>
            <value>
                <fullName>Client Project</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Maternity Leave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Calendar__c/Work_Calendar__c.object-meta.xml
<CustomObject>
    <label>Work Calendar</label>
    <nameField>
        <label>Work Calendar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Calendar__c/fields/Assignment__c.field-meta.xml
<CustomField>
    <fullName>Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assignment</label>
    <referenceTo>Assignment__c</referenceTo>
    <relationshipLabel>Work Calendar</relationshipLabel>
    <relationshipName>Work_Calendar</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Calendar__c/fields/Monday_Hours__c.field-meta.xml
<CustomField>
    <fullName>Monday_Hours__c</fullName>
    <label>Monday Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Work_Calendar__c/fields/Saturday_Hours__c.field-meta.xml
<CustomField>
    <fullName>Saturday_Hours__c</fullName>
    <label>Saturday Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Work_Calendar__c/fields/Thursday_Hours__c.field-meta.xml
<CustomField>
    <fullName>Thursday_Hours__c</fullName>
    <label>Thursday Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Work_Calendar__c/fields/Tuesday_Hours__c.field-meta.xml
<CustomField>
    <fullName>Tuesday_Hours__c</fullName>
    <label>Tuesday Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Work_Calendar__c/fields/Wednesday_Hours__c.field-meta.xml
<CustomField>
    <fullName>Wednesday_Hours__c</fullName>
    <label>Wednesday Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TimecardController.cls
public with sharing class TimecardController {

    // Method to fetch timecards for the current user
    @AuraEnabled
    public static WeekWrapper getTimecardsByUser(String startDate, String endDate, String objectApiName, String recordId) {
        Date startDateValue = Date.valueOf(startDate);
        Date endDateValue = Date.valueOf(endDate);

        List<Internal_Activities__c> absences = getAbsenceFieldsInQuery();
        String abnseceFields = '';

        for( Internal_Activities__c curActivity : absences ) {
            abnseceFields += ' , ' + curActivity.Allowed_Absence_Field__c;
            abnseceFields += ' , ' + curActivity.Availability_Field__c;
        }

        // Fetch the current user's Resource
        Id userId = UserInfo.getUserId();
        String resourceQuery = 'SELECT Id, Region__c, Region__r.Work_Calendar__c ' + abnseceFields + ' FROM Resource__c WHERE User__c = :userId LIMIT 1';
        Resource__c currentResource = Database.query( resourceQuery );
        Id currentResourceId = currentResource.Id;


        // Base query to fetch timecards for the user
        String query = 'SELECT Id, Name, Resource__r.Name, ' +
                'Monday_Hours__c, Tuesday_Hours__c, ' +
                'Wednesday_Hours__c, Thursday_Hours__c, ' +
                'Friday_Hours__c, Saturday_Hours__c, ' +
                'Sunday_Hours__c, Total_Billiable_Amount__c, ' +
                'Start_Date__c, End_Date__c, Type__c, ' +
                'Project__r.Name, Assignment__r.Name, ' +
                'Milestone__r.Name, Total_Hours__c, Status__c ' +
                'FROM Timecard__c WHERE Resource__c = :currentResourceId ' +
                'AND Start_Date__c >= :startDateValue AND End_Date__c <= :endDateValue';

        // Conditionally add filters based on the objectApiName passed (e.g., Project, Assignment)
        if (objectApiName != null) {
            if (objectApiName == 'Project__c') {
                query += ' AND Project__c =: recordId';
            } else if (objectApiName == 'Assignment__c') {
                query += ' AND Assignment__c  =: recordId';
            } else if (objectApiName == 'Milestone__c') {
                query += ' AND Milestone__c  =: recordId';
            }
        }

        // Filter by the recordId if necessary
        if (recordId != null) {
            query += ' AND (Project__c = :recordId OR Assignment__c = :recordId)';
        }

        List<Timecard__c> timecards = Database.query(query);

        List<TimecardWrapper> timecardData = new List<TimecardWrapper>();

        for (Timecard__c tc : timecards) {
            TimecardWrapper tw = new TimecardWrapper();
            tw.timecardName = tc.Name;
            tw.resourceName = tc.Resource__r.Name;
            tw.mondayHours = tc.Monday_Hours__c;
            tw.tuesdayHours = tc.Tuesday_Hours__c;
            tw.wednesdayHours = tc.Wednesday_Hours__c;
            tw.thursdayHours = tc.Thursday_Hours__c;
            tw.fridayHours = tc.Friday_Hours__c;
            tw.saturdayHours = tc.Saturday_Hours__c;
            tw.sundayHours = tc.Sunday_Hours__c;
            tw.totalHours = tc.Total_Hours__c;
            tw.totalBillableAmount = tc.Total_Billiable_Amount__c;
            tw.projectName = tc.Project__r.Name;
            tw.assignmentName = tc.Assignment__r.Name;
            tw.milestoneName = tc.Milestone__r.Name;
            tw.type = tc.Type__c;
            tw.status = tc.Status__c;
            tw.Id = tc.Id;
            timecardData.add(tw);
        }
        WeekWrapper result = new WeekWrapper();
        result.holidays = getHolidays(startDate, endDate, currentResource.Region__r.Work_Calendar__c);
        result.scheduledTime = getScheduledTime(currentResourceId);
        result.timecards = timecardData;

        List<AbsenceWrapper> absenceWrappers = new List<TimecardController.AbsenceWrapper>();
        for( Internal_Activities__c curActivity : absences ) {
            AbsenceWrapper curAbs = new AbsenceWrapper();
            curAbs.name = curActivity.Name;
            curAbs.allowed = currentResource.get( curActivity.Allowed_Absence_Field__c ).toString();
            curAbs.remaining = currentResource.get( curActivity.Availability_Field__c ).toString();
            curAbs.used = String.valueOf( ( Decimal ) currentResource.get( curActivity.Allowed_Absence_Field__c ) - ( Decimal ) currentResource.get( curActivity.Availability_Field__c ) );
            absenceWrappers.add( curAbs );
        }
System.debug(absenceWrappers);
        result.absences = absenceWrappers;


        return result;
    }

    public static List<ScheduledWeekTime> getScheduledTime( Id resourceId ) {
        List<ScheduledWeekTime> result = new List<ScheduledWeekTime>();
        List<Assignment__c> existingAssignments = [SELECT Id, Project__r.Name, Project__r.Daily_Timecart_Notes_Required__c, Overtime__c, Percent_Allocated__c FROM Assignment__c WHERE Resource__c = :resourceId AND Status__c = 'Active'];
        for( Assignment__c assignment : existingAssignments ) {
            ScheduledWeekTime swt = new ScheduledWeekTime();
            swt.projectName = assignment.Project__r.Name;
            swt.requiredHours = String.valueOf( 40 * assignment.Percent_Allocated__c / 100);
            swt.isDailyNotesRequired = assignment.Project__r.Daily_Timecart_Notes_Required__c;
            swt.isOvertime = assignment.Overtime__c;
            result.add(swt);
        }
        return result;
    }

    public static List<Internal_Activities__c> getAbsenceFieldsInQuery() {
        List<Internal_Activities__c> result = new List<Internal_Activities__c>();
        for( Internal_Activities__c curActivity : Utilities.getInternalActivitiesProjectMap().values() ) {
            if( String.isNotBlank( curActivity.Allowed_Absence_Field__c ) && String.isNotBlank( curActivity.Availability_Field__c ) ) {
                result.add( curActivity );
            }
        }
        return result;
    }

    @AuraEnabled
    public static String getCurrentResource() {
        Resource__c currentUser = [SELECT Id FROM Resource__c WHERE User__c = :UserInfo.getUserId() LIMIT 1];
        return currentUser.Id;
    }

    @AuraEnabled
    public static void deleteTimecard( Id timecardId ) {
        delete new Timecard__c( Id = timecardId );
    }

    @AuraEnabled
    public static void submitTimecard( List<Id> timecardIds ) {
        List<Timecard__c> timecards = [SELECT Id, Project__r.OwnerId, Status__c FROM Timecard__c WHERE Id IN :timecardIds];
        List<Approval.ProcessRequest> recordsForApproval = new List<Approval.ProcessRequest>();
        for( Timecard__c curCart : timecards ) {
            if( curCart.Status__c != 'Approved' && curCart.Status__c != 'Submitted' ) {
                Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
                req.setObjectId( curCart.Id );
                List<Id> approverIds = new List<Id>{ curCart.Project__r.OwnerId };
                req.setNextApproverIds(approverIds);

                recordsForApproval.add( req );
            }
        }

        String errors = '';
        List<Approval.ProcessResult> result = Approval.process( recordsForApproval );
        for( Approval.ProcessResult res : result ) {
            if( !res.isSuccess() ) {
                errors += res.getErrors()[0].getMessage() + '\n';
            }
        }

        if( String.isNotBlank( errors ) ) {
            throw new AuraHandledException( errors );
        }

    }

    public class WeekWrapper {
        @AuraEnabled
        public List<ScheduledWeekTime> scheduledTime;
        @AuraEnabled
        public List<TimecardWrapper> timecards;
        @AuraEnabled
        public List<Holidays__c> holidays;
        @AuraEnabled
        public List<AbsenceWrapper> absences;
    }

    public class ScheduledWeekTime {
        @AuraEnabled
        public String projectName;
        @AuraEnabled
        public String requiredHours;
        @AuraEnabled
        public Boolean isDailyNotesRequired;
        @AuraEnabled
        public Boolean isOvertime;
    }

    public class AbsenceWrapper {
        @AuraEnabled
        public String name;
        @AuraEnabled
        public String used;
        @AuraEnabled
        public String allowed;
        @AuraEnabled
        public String remaining;
    }

    public class TimecardWrapper {
        @AuraEnabled
        public String timecardName;
        @AuraEnabled
        public String resourceName;
        @AuraEnabled
        public Decimal mondayHours;
        @AuraEnabled
        public Decimal tuesdayHours;
        @AuraEnabled
        public Decimal wednesdayHours;
        @AuraEnabled
        public Decimal thursdayHours;
        @AuraEnabled
        public Decimal fridayHours;
        @AuraEnabled
        public Decimal saturdayHours;
        @AuraEnabled
        public Decimal sundayHours;
        @AuraEnabled
        public Decimal totalHours;
        @AuraEnabled
        public Decimal totalBillableAmount;
        @AuraEnabled
        public String projectName;
        @AuraEnabled
        public String assignmentName;
        @AuraEnabled
        public String milestoneName;
        @AuraEnabled
        public String type;
        @AuraEnabled
        public String status;
        @AuraEnabled
        public String Id;
    }

    public static List<Holidays__c> getHolidays(String startDate, String endDate, Id workCalendarId) {
        Date startDateValue = Date.valueOf(startDate);
        Date endDateValue = Date.valueOf(endDate);

        List<Holidays__c> holidays = [SELECT Id, Name, Date__c FROM Holidays__c WHERE Date__c >= :startDateValue AND Date__c <= :endDateValue AND Work_Calendar__c = :workCalendarId];

        return ( holidays != null && holidays.size() != 0 ) ? holidays : null;
    }

}