force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Skill__c/Resource_Skill__c.object-meta.xml
<CustomObject>
    <label>Resource Skill</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Resource Skills Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Skill__c/fields/Date_of_Receipt__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Receipt__c</fullName>
    <description>The Date of Receipt Certification field is used to record the exact date when a company or individual officially receives a certification confirming compliance with specific standards, requirements, or criteria.</description>
    <label>Date of Receipt</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Resource_Skill__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>The exact date when a certification is set to expire. This field is essential for ensuring that certifications remain current and that renewal processes are managed effectively.</description>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Resource_Skill__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <description>Field for entering a rating that allows values from 1 to 5, where 1 is the lowest rating and 5 is the highest. Used to assess quality, performance, of skill.</description>
    <inlineHelpText>Enter a skill rating from 1 to 5 range.</inlineHelpText>
    <label>Rating</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Resource_Skill__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Resource Skills</relationshipLabel>
    <relationshipName>Resource_Skills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resource_Skill__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <label>Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipLabel>Resource Skills</relationshipLabel>
    <relationshipName>Resource_Skills</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Skills Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Skill</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SkillsController.cls
public with sharing class SkillsController {

    @AuraEnabled(cacheable=true)
    public static Map<String, List<Resource_Skill__c>>  getSkillsByUser(Id userId) {
        Map<String, List<Resource_Skill__c>> skillsByType = new Map<String, List<Resource_Skill__c>>();
        Resource__c resource = [SELECT Id FROM Resource__c WHERE User__c = :userId LIMIT 1];

        if (resource != null) {
            List<Resource_Skill__c> skills = [
                    SELECT Skill__r.Name, Skill__r.Type__c, Rating__c, Date_of_Receipt__c, Expiration_Date__c
                    FROM Resource_Skill__c
                    WHERE Resource__c = :resource.Id
            ];

            for( Resource_Skill__c curSkill : skills ) {
                if( !skillsByType.containsKey( curSkill.Skill__r.Type__c ) ) {
                    skillsByType.put( curSkill.Skill__r.Type__c, new List<Resource_Skill__c>() );
                }
                skillsByType.get( curSkill.Skill__r.Type__c ).add( curSkill );
            }
            return skillsByType;
        }
        return new Map<String, List<Resource_Skill__c>>();
    }
}